[package]
name = "deptriage"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.58", features = ["derive"] }
color-eyre = "0.6.5"
comfy-table = "7.2.2"
ratatui = "0.30.0"
serde = { version = "1.0.228", features = ['derive'] }
serde_json = "1.0.149"
